### ISSUE TITLE
[Feature]: Enhance the basic CLI features

### ISSUE THREAD

**Issue by RezaRahemtola** [PoCInnovation/SecureEnv#28]
### Description

Enable a better local integration in your CLI :fire: 

### Expected behaviour

You have to use a system similar to git:
- [x] When a command is executed, look in the current directory for a `.env` file to load
- [x] It should be possible to `push` changes to the vault (read the `.env` file, take all the variables excepted the ones starting with `SECURE_ENV_` and save them in the vault using the API)
- [x] It should be possible to `pull` changes to the vault (get the vault using the API and write to the `.env` file)
- [x] It should be possible to view the `status` of the variables (which one are outdated, new, modified...)
- [x] Check with the API team to see how you can integrate these features

### Environment

/

**Comment by Matribuk** [comment]
Issue done, all task is finished.
